[package]
name = "retrie"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
derive_builder = "0.12.0"

[dev-dependencies]
proptest = "1.0.0"
test-case = "2.2.2"
